### ISSUE TITLE
Redis Demo "WebJobs in real scenarios #2: Faster ASP.NET" Not found

### ISSUE THREAD

**Issue by JuanKRuiz** [Azure-Readiness/DevCamp#6]
Hi, 
Redis Demo "WebJobs in real scenarios #2: Faster ASP.NET" It's supposed to be in **/DevCamp-master\Presentation\Web**

This isn't in this repository.

**Comment by jongalloway** [comment]
I'm not sure what the issue is. Where is the reference to a WebJobs demo?

Are you asking about this demo? https://github.com/Azure-Readiness/DevCamp/tree/master/Presentation/Web/Demo2%20-%20Cache%20Azure%20Table%20Storage/source

**Comment by JuanKRuiz** [comment]
No, that one has another problems XD 

The one I'm asking for is the one in slide #45 "Redis Cache for ASP Session state".

But I'm just  reading the comments in the slide saying you can get the demo here .

http://azure.microsoft.com/en-us/documentation/articles/web-sites-dotnet-session-state-caching
