### ISSUE TITLE
HOL readme.html files are missing. 

### ISSUE THREAD

**Issue by BretStateham** [Azure-Readiness/DevCamp#9]
We need to generate the .html version of the readmes for camp attendees so they don't have to read the .md source. This needs to be done for each of the HOLs and the .html files need to be updated if the .md files are changed in the future.

**Comment by jongalloway** [comment]
HTML for all readme files is included in the installer: https://github.com/Azure-Readiness/DevCamp/releases/latest

This includes HTML with a Bootstrap based (responsive) stylesheet and all NuGet packages for use offline.

**Comment by BretStateham** [comment]
Thanks for clarifying.  We might want to add mention of, and a link to, the installer on the repo's readme.md.
